/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class', // Enable dark mode based on 'dark' class
  theme: {
    extend: {
      // Define custom colors using CSS variables
      colors: {
        // Catppuccin Macchiato (Dark)
        'ctp-macchiato-rosewater': 'rgb(var(--ctp-macchiato-rosewater) / <alpha-value>)',
        'ctp-macchiato-flamingo': 'rgb(var(--ctp-macchiato-flamingo) / <alpha-value>)',
        'ctp-macchiato-pink': 'rgb(var(--ctp-macchiato-pink) / <alpha-value>)',
        'ctp-macchiato-mauve': 'rgb(var(--ctp-macchiato-mauve) / <alpha-value>)',
        'ctp-macchiato-red': 'rgb(var(--ctp-macchiato-red) / <alpha-value>)',
        'ctp-macchiato-maroon': 'rgb(var(--ctp-macchiato-maroon) / <alpha-value>)',
        'ctp-macchiato-peach': 'rgb(var(--ctp-macchiato-peach) / <alpha-value>)',
        'ctp-macchiato-yellow': 'rgb(var(--ctp-macchiato-yellow) / <alpha-value>)',
        'ctp-macchiato-green': 'rgb(var(--ctp-macchiato-green) / <alpha-value>)',
        'ctp-macchiato-teal': 'rgb(var(--ctp-macchiato-teal) / <alpha-value>)',
        'ctp-macchiato-sky': 'rgb(var(--ctp-macchiato-sky) / <alpha-value>)',
        'ctp-macchiato-sapphire': 'rgb(var(--ctp-macchiato-sapphire) / <alpha-value>)',
        'ctp-macchiato-blue': 'rgb(var(--ctp-macchiato-blue) / <alpha-value>)',
        'ctp-macchiato-lavender': 'rgb(var(--ctp-macchiato-lavender) / <alpha-value>)',
        'ctp-macchiato-text': 'rgb(var(--ctp-macchiato-text) / <alpha-value>)',
        'ctp-macchiato-subtext1': 'rgb(var(--ctp-macchiato-subtext1) / <alpha-value>)',
        'ctp-macchiato-subtext0': 'rgb(var(--ctp-macchiato-subtext0) / <alpha-value>)',
        'ctp-macchiato-overlay2': 'rgb(var(--ctp-macchiato-overlay2) / <alpha-value>)',
        'ctp-macchiato-overlay1': 'rgb(var(--ctp-macchiato-overlay1) / <alpha-value>)',
        'ctp-macchiato-overlay0': 'rgb(var(--ctp-macchiato-overlay0) / <alpha-value>)',
        'ctp-macchiato-surface2': 'rgb(var(--ctp-macchiato-surface2) / <alpha-value>)',
        'ctp-macchiato-surface1': 'rgb(var(--ctp-macchiato-surface1) / <alpha-value>)',
        'ctp-macchiato-surface0': 'rgb(var(--ctp-macchiato-surface0) / <alpha-value>)',
        'ctp-macchiato-base': 'rgb(var(--ctp-macchiato-base) / <alpha-value>)',
        'ctp-macchiato-mantle': 'rgb(var(--ctp-macchiato-mantle) / <alpha-value>)',
        'ctp-macchiato-crust': 'rgb(var(--ctp-macchiato-crust) / <alpha-value>)',

        // Catppuccin Latte (Light)
        'ctp-latte-rosewater': 'rgb(var(--ctp-latte-rosewater) / <alpha-value>)',
        'ctp-latte-flamingo': 'rgb(var(--ctp-latte-flamingo) / <alpha-value>)',
        'ctp-latte-pink': 'rgb(var(--ctp-latte-pink) / <alpha-value>)',
        'ctp-latte-mauve': 'rgb(var(--ctp-latte-mauve) / <alpha-value>)',
        'ctp-latte-red': 'rgb(var(--ctp-latte-red) / <alpha-value>)',
        'ctp-latte-maroon': 'rgb(var(--ctp-latte-maroon) / <alpha-value>)',
        'ctp-latte-peach': 'rgb(var(--ctp-latte-peach) / <alpha-value>)',
        'ctp-latte-yellow': 'rgb(var(--ctp-latte-yellow) / <alpha-value>)',
        'ctp-latte-green': 'rgb(var(--ctp-latte-green) / <alpha-value>)',
        'ctp-latte-teal': 'rgb(var(--ctp-latte-teal) / <alpha-value>)',
        'ctp-latte-sky': 'rgb(var(--ctp-latte-sky) / <alpha-value>)',
        'ctp-latte-sapphire': 'rgb(var(--ctp-latte-sapphire) / <alpha-value>)',
        'ctp-latte-blue': 'rgb(var(--ctp-latte-blue) / <alpha-value>)',
        'ctp-latte-lavender': 'rgb(var(--ctp-latte-lavender) / <alpha-value>)',
        'ctp-latte-text': 'rgb(var(--ctp-latte-text) / <alpha-value>)',
        'ctp-latte-subtext1': 'rgb(var(--ctp-latte-subtext1) / <alpha-value>)',
        'ctp-latte-subtext0': 'rgb(var(--ctp-latte-subtext0) / <alpha-value>)',
        'ctp-latte-overlay2': 'rgb(var(--ctp-latte-overlay2) / <alpha-value>)',
        'ctp-latte-overlay1': 'rgb(var(--ctp-latte-overlay1) / <alpha-value>)',
        'ctp-latte-overlay0': 'rgb(var(--ctp-latte-overlay0) / <alpha-value>)',
        'ctp-latte-surface2': 'rgb(var(--ctp-latte-surface2) / <alpha-value>)',
        'ctp-latte-surface1': 'rgb(var(--ctp-latte-surface1) / <alpha-value>)',
        'ctp-latte-surface0': 'rgb(var(--ctp-latte-surface0) / <alpha-value>)',
        'ctp-latte-base': 'rgb(var(--ctp-latte-base) / <alpha-value>)',
        'ctp-latte-mantle': 'rgb(var(--ctp-latte-mantle) / <alpha-value>)',
        'ctp-latte-crust': 'rgb(var(--ctp-latte-crust) / <alpha-value>)',

        // Tokyo Night (Dark)
        'tokyo-night-dark-bg': 'rgb(var(--tokyo-night-dark-bg) / <alpha-value>)',
        'tokyo-night-dark-fg': 'rgb(var(--tokyo-night-dark-fg) / <alpha-value>)',
        'tokyo-night-dark-red': 'rgb(var(--tokyo-night-dark-red) / <alpha-value>)',
        'tokyo-night-dark-green': 'rgb(var(--tokyo-night-dark-green) / <alpha-value>)',
        'tokyo-night-dark-yellow': 'rgb(var(--tokyo-night-dark-yellow) / <alpha-value>)',
        'tokyo-night-dark-blue': 'rgb(var(--tokyo-night-dark-blue) / <alpha-value>)',
        'tokyo-night-dark-magenta': 'rgb(var(--tokyo-night-dark-magenta) / <alpha-value>)',
        'tokyo-night-dark-cyan': 'rgb(var(--tokyo-night-dark-cyan) / <alpha-value>)',
        'tokyo-night-dark-white': 'rgb(var(--tokyo-night-dark-white) / <alpha-value>)',
        'tokyo-night-dark-black': 'rgb(var(--tokyo-night-dark-black) / <alpha-value>)',

        // Tokyo Night Light (Light)
        'tokyo-night-light-bg': 'rgb(var(--tokyo-night-light-bg) / <alpha-value>)',
        'tokyo-night-light-fg': 'rgb(var(--tokyo-night-light-fg) / <alpha-value>)',
        'tokyo-night-light-red': 'rgb(var(--tokyo-night-light-red) / <alpha-value>)',
        'tokyo-night-light-green': 'rgb(var(--tokyo-night-light-green) / <alpha-value>)',
        'tokyo-night-light-yellow': 'rgb(var(--tokyo-night-light-yellow) / <alpha-value>)',
        'tokyo-night-light-blue': 'rgb(var(--tokyo-night-light-blue) / <alpha-value>)',
        'tokyo-night-light-magenta': 'rgb(var(--tokyo-night-light-magenta) / <alpha-value>)',
        'tokyo-night-light-cyan': 'rgb(var(--tokyo-night-light-cyan) / <alpha-value>)',
        'tokyo-night-light-white': 'rgb(var(--tokyo-night-light-white) / <alpha-value>)',
        'tokyo-night-light-black': 'rgb(var(--tokyo-night-light-black) / <alpha-value>)',
      },
    },
  },
  plugins: [],
}
